server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2MB      # 文件上传大小限制，设置最大值，不能超过该值，否则报错
      #      max-file-size: 500KB      # 文件上传大小限制，设置最大值，不能超过该值，否则报错
      max-request-size: 2MB     # 文件最大请求限制，用于批量上传
      #      max-request-size: 500KB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 整合mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true          # 开启驼峰命名匹配
    auto-mapping-behavior: full                 # 自动映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql执行语句
    mapper-locations: classpath:mapper/*.xml    # mapper映射文件
  type-aliases-package: com.javahome.wine.model # 实体映射
  global-config:                                # 全局配置
    db-config:
      id-type: auto                             # 设置主键自增
      logic-delete-field: deleted               # 逻辑删除字段
      logic-delete-value: 1                     # 逻辑已删除
      logic-not-delete-value: 0                 # 逻辑未删除



## 分页插件助手的配置
#pagehelper:
#  helper-dialect: MYSQL
#  support-methods-arguments: true

# 日志级别
logging:
  level:
    root: info