server:
  port: 8096

spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://192.168.43.20:3306/practice?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  redis:
    host: 192.168.0.111
    port: 6379
    database: 0
    password: 123456

# fastDfs 配置
fdfs:
  connect-timeout: 2000                   # socket连接超时时间
  so-timeout: 1500                        # tracker服务器超时时间
  thumb-image:                            # 缩略图相关,宽、高
    width: 60
    height: 60
  tracker-list: localhost:22122            # tracker服务配置地址列表，可配置多个
#  pool:                                    # 连接池相关
#    max-total: 200                         # 连接池最大数量
#    max-total-per-key: 50                  # 单个tracker最大连接数
#    max-wait-millis: 5000                  # 连接耗尽最大等待时间 毫秒